### ISSUE TITLE
Files missing from npm package

### ISSUE THREAD

**Issue by bsyk** [75lb/command-line-usage#24]
The `lib/section/` folder is missing from the npm package in v6.0.0, which causes runtime errors such as below:

```
Error: Cannot find module './lib/section/option-list'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at commandLineUsage (/Users/xxx/workspace/proj/node_modules/command-line-usage/index.js:15:24)
```

Verified the files are missing by downloading/unzipping from npm directly:
```
curl -O https://registry.npmjs.org/command-line-usage/-/command-line-usage-6.0.0.tgz
```

**Comment by 75lb** [comment]
tsk, that's one thing the travis tests fail to pick up on.. thanks for letting me know - it's fixed, please reinstall.
